# Makefile.in generated by automake 1.11.1 from Makefile.am.
# cgicc/Makefile.  Generated from Makefile.in by configure.

ifdef STRIP
	STRIP = true
else
	STRIP = false
endif

CXX=g++ -Wall -Wextra -std=c++0x
CXXFLAGS=
INCLUDES=-I. -I..
AR=ar
RANLIB=ranlib
GUESS_CHOST=./config.guess
MKDEF=./mkdefine
PACKAGE=cgi-m0sh
VERSION=0.1

libcgicc_so_SOURCES = cgi/*/*.so
libcgicc_a_SOURCES = cgi/*/*/*.a

all: cgi/config.h libcgicc.so libcgicc.a

libcgicc.a: $(addsuffix -static.o, $(addprefix out/, $(basename $(libcgicc_SOURCES)))) | out
	$(AR) rc $@ $^
	$(RANLIB) $@
ifeq ($(STRIP), true)
	strip --strip-unneeded -S libcgicc.a
endif

libcgicc.so: $(addsuffix -shared.o, $(addprefix out/, $(basename $(libcgicc_SOURCES)))) | out
	$(CXX) $(CXXFLAGS) -shared -fPIC -o $@ $^ $(INCLUDES)
ifeq ($(STRIP),true)
	strip -s libcgicc.so
endif

out/%-static.o: cgi/%.cpp cgi/%.h cgi/config.h | out
	$(CXX) $(CXXFLAGS) -o $@ -c $< $(INCLUDES)

out/%-shared.o: cgi/%.cpp cgi/%.h cgi/config.h | out
	$(CXX) $(CXXFLAGS) -fPIC -o $@ -c $< $(INCLUDES)

out:
	mkdir $@

cgicc/config.h:
	$(shell $(MKDEF) -p HOST $(GUESS_CHOST) > $@)
	$(shell $(MKDEF) PACKAGE $(PACKAGE) >> $@)
	$(shell $(MKDEF) VERSION $(VERSION) >> $@)
	$(shell $(MKDEF) -w WORDSIZE >> $@)

clean:
	rm out/*
	rm cgi/config.h
