#!/usr/bin/perl -w
use File::Temp qw/ :POSIX /;
my $prog;
my $preout;
my $sym;
if ($ARGV[0] =~ /-p/) {
	shift @ARGV;
	$sym = $ARGV[0]; shift @ARGV;
	$prog = join(' ', @ARGV);
	my $pre = qx($prog);
	chomp $pre;
	$preout = "\"$pre\"";
} elsif ($ARGV[0] =~ /--?w(ordsize)?/) {
	my $f = tmpnam();
	system 'echo -e \'#include <stddef.h>\n#include <limits.h>\nint main(){return CHAR_BIT*sizeof(size_t);}\' | gcc -x c - -o '.$f;
	$preout = ((system $f)/256);
	$sym = $ARGV[1];
	unlink $f;
} else {
	$sym = $ARGV[0];
	shift @ARGV;
	$preout = "\"".join(' ', @ARGV)."\"";
}

print "#define $sym $preout\n";

