#!/bin/bash
OLDDIR="$(pwd)"
MYTARGET="$(pwd)/$1"
shift;
MYDIR=$(tempfile)
rm $MYDIR
mkdir $MYDIR
cd $MYDIR
for lib in $*; do
	ar x "$OLDDIR/$lib"
done
ar cr "$MYTARGET" *
ranlib "$MYTARGET"
cd "$OLDDIR"
rm -rf $MYDIR

